### ISSUE TITLE
unknown account model when moving to org

### ISSUE THREAD

**Issue by nrdxp** [hercules-ci/support#54]
I moved my project from my personal repo nrdxp/nixlfk to an organization divnix.com/devos, and got the error:
```sh
Unknown account model #... hash ommitted
```
from the dashboard

It doesn't seem to want to build the project, asking me to add a nix file, when in fact there is already one.

**Comment by roberth** [comment]
I will look into it today.

**Comment by roberth** [comment]
It seems like the move + fork combination confused the integration logic. I've fixed up the data manually and I have found a way to improve the logic.
You can now enable CI for your repo https://hercules-ci.com/github/divnix/devos and give it a try by pushing a ref or new commit.

**Comment by nrdxp** [comment]
Thank you, but unfortunately it's still not detecting the new repo

**Comment by roberth** [comment]
I see. According to the backend logs, github says "This installation has been suspended". You can probably unsuspend it here https://github.com/organizations/hercules-ci/settings/installations/14798673

**Comment by nrdxp** [comment]
Stange, it is definitely not suspended. I tried suspending it to see if that might help, but that was for less than a minute:
![image](https://user-images.githubusercontent.com/34083928/108564294-1960e580-72c0-11eb-8449-2402d83cab5d.png)

**Comment by nrdxp** [comment]
The issue seems to be with the entire divnix organization, as I added a test repo to see if hercules would build it, and it's giving the same error, namely reporting that I need to add a nix file when one already exists.

**Comment by roberth** [comment]
Did you add the other divnix repo in the github installation ui?
The github api indicates you're using a selection.

**Comment by nrdxp** [comment]
### I've reset everything to as liberal as possible:
![image](https://user-images.githubusercontent.com/34083928/108613892-34605200-73b3-11eb-86cc-e04275b05ab2.png)

### also ensuring:
![image](https://user-images.githubusercontent.com/34083928/108613702-8acc9100-73b1-11eb-8bd8-e6c43800d483.png)
is on for the relevant repos.



### context
nrdxp/devos won't build either, so I used [nrdxp/devshell](https://hercules-ci.com/github/nrdxp/devshell) as a baseline and it works, but the same repo [divnix/devshell](https://hercules-ci.com/github/divnix/devshell) fails. 

Also, I didn't seem to mention up above, but yesterday I got the same "unknown account model" error even after your fixes.

**Comment by roberth** [comment]
I've corrected a mistake I made while correcting the integration data. Jobs are appearing in the devos repo now. Those should start evaluating when you bring your divnix agent back online.

**Comment by roberth** [comment]
Another correction is necessary to unblock evaluations. Might take a minute.

**Comment by roberth** [comment]
Please ping me when you've restarted the agent.

**Comment by nrdxp** [comment]
@roberth agent is up now.

**Comment by roberth** [comment]
Thanks! I'm troubleshooting the issue.

**Comment by nrdxp** [comment]
Just heard my fans spin up, and sure enough evaluation just picked up for some missed jobs. Thaks for all the hard work!

**Comment by roberth** [comment]
Just wanted to tell you :)
